---
- name: Configure port group
  hosts: localhost
  gather_facts: False
  vars_files:
    - ../cfg_esxi.vars.yml
  tasks:
    - name: add standard portgroup to virtual switch
      vmware_vm_shell:
        hostname: "{{ vcenter.vcenter_hostname }}"
        username: "{{ vcenter.vcenter_username }}"
        password: "{{ vcenter.vcenter_password }}"
        datacenter: "{{ vcenter.datacenter }}"
        validate_certs: false
        vm_id: "{{ item.key }}"
        vm_username: "{{ esxi_shell.username }}"
        vm_password: "{{ esxi_shell.password }}"
        vm_shell: /bin/esxcli
        vm_shell_args: "network vswitch standard portgroup add --portgroup-name='VM Network' --vswitch-name='vSwitch0'"
        vm_shell_env: 
        - "PATH=/bin"
        - "VAR=test"
        vm_shell_cwd: "/tmp"
      with_dict: "{{ vESX1 }}"
      async: 7200
      poll: 0
      register: hvlan